development: &default
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['DATABASE_NAME'] || 'efishery_user_api' %>
  host: <%= ENV['DATABASE_HOST'] || '127.0.0.1' %>
  port: <%= ENV['DATABASE_PORT'] || 3306 %>
  pool: <%= ENV['DATABASE_POOL'] || 5 %>
  username: <%= ENV['DATABASE_USER'] || 'root' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '' %>

production:
  <<: *default
  reconnect: false
  database: <%= ENV['DATABASE_NAME'] || 'efishery_user_api_prod' %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  pool: <%= ENV['DATABASE_POOL'] || 50 %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: <%= ENV['DATABASE_TEST_NAME'] || 'efishery_user_api_test' %>
